### ISSUE TITLE
How to Start?

### ISSUE THREAD

**Issue by LordBroll** [Vadmeme/BTD6Internal#1]
What for a Programm do you use to start this?

**Comment by LordBroll** [comment]
I have been a registered member of GitHub for a long time, but today is the first time I sit down with it :-) Could you explain it in a way that even a fool understands it?

**Comment by LordBroll** [comment]
Do I only need a cheat engine for that? If so, I can't find the table :-/ I would even be willing to pay for it! Get in touch :-)

**Comment by Vadmeme** [comment]
the offsets in this are old so most features wont work, as i havent updated it

it is relativeley easy to update the sdk headers
rest is sig based so good luck
